version: '3'

vars:
  AQUA_ROOT_DIR:
    sh: echo "${AQUA_ROOT_DIR:-${XDG_DATA_HOME:-$HOME/.local/share}/aquaproj-aqua}"

env:
  PATH: "{{.AQUA_ROOT_DIR}}/bin:{{.PATH}}"

tasks:
  tf-init:
    deps: [setup-aqua]
    cmds:
      - terraform init

  setup-aqua:
    cmds:
      - bash scripts/setup_aqua.sh
